obj-$(CONFIG_JASONTEK_SHELLDEMO) += shelldemo.o
obj-$(CONFIG_JASONTEK_SYNCDEMO)  += syncdemo.o
obj-$(CONFIG_JASONTEK_BTNDEMO)   += btndemo.o
obj-$(CONFIG_JASONTEK_PHILDEMO)  += phildemo.o
obj-$(CONFIG_JASONTEK_PWMDEMO)   += pwmdemo.o

obj-y                            += main.o
